### PR TITLE
Create perlmutter_cpu_homme.sh

### PR DESCRIPTION
**Pull request by wadeburgess**
Create new script for running homme_integration on pm-cpu

### CODE REVIEW

**Review by jgfouca — APPROVED** [review]

**Comment by oksanaguba** [comment]
@jgfouca or @wadeburgess  -- why do we have this for pm-cpu, not pm-gpu?

**Comment by rljacob** [comment]
I did.  Don't we only run the homme_integration suite on cpus?

Also I noticed that we don't run the homme suite on perlmutter and seems like we should since its our main "public" machine.

**Comment by oksanaguba** [comment]
homme suite can run on a gpu, and we'd really like to have such nightlies. it may be that homme needs new cache files for that, we will look at this in the next few days.

**Comment by rljacob** [comment]
There's also this PR which was motivation:  https://github.com/E3SM-Project/E3SM/pull/6114

**Comment by mt5555** [comment]
one issue:  perlmutter default is Intel, and HOMME doesn't have an intel machine file.  The one in https://github.com/E3SM-Project/E3SM/pull/6114 is tweaking the GNU machine file to not disable output.  

Today I started working on a Intel machine file for HOMME, but if someone already has one, let me know.

**Comment by oksanaguba** [comment]
@mt5555 why would we want intel file? we already run with intel on chrysalis, don't we want gnu instead? also, i do not see much value in running intel+cpu on PM, let's do gnu+gpu?

**Pull request merged**
