### PR TITLE
Create anvil_maint

### PR DESCRIPTION
**Pull request by wadeburgess**
Not sure if this is correct, but it is a start.

### CODE REVIEW

**Comment by rljacob** [comment]
I'm realizing I don't know enough about the system to approve this.  It looks ok.  But I don't see here or in the cori-knl and compy maint scripts how the specific maint branch is selected.  How does it know to do maint-2.0 ?

**Comment by wadeburgess** [comment]
@jgfouca  Can you help us out here? Rob asked a question....

**Comment by jgfouca** [comment]
@rljacob , @wadeburgess , the default behavior is to use the current branch name as the baseline name.

**Review by jgfouca — APPROVED** [review]

**Comment by rljacob** [comment]
Where is the checkout of maint-2.0 done then?

**Pull request merged**
